# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 'lts/fermium'

    # We also move the prebuilt opus file because app service uses 2.28 to annoy people
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        mv ./node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.27/ ./node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28/
        rm -rf ./pics

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: eolian-webapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_40B351E1A44940C38773B87C7B8D63A0 }}
        package: .

